sudo: required

dist: trusty

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js

node_js:
  - "7"
  
install:
  - yarn install
  - yarn add electron-builder -dev
script:
  - yarn run dist
