version: 0.4.{build}

platform:
  - x64

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 7 x64
  - yarn install
  - yarn add electron-builder@next --dev # force install next version to test electron-builder

build_script:
  - yarn run dist

test: off
deploy:
  release: electron-start-kit-v$(appveyor_build_version)
  description: 'Release description'
  provider: GitHub
  auth_token: ab32f2871836963f7ae9294ba9f99ce45e5d2f8c
  draft: true
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only
