version: 0.4.{build}

platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 7 x64
  - yarn install
  - yarn add electron-builder@next --dev # force install next version to test electron-builder

build_script:
  - yarn run dist

test: off

artifacts:
- path: build
  name: buildzip
  type: WebDeployPackage
  
deploy:
- provider: GitHub
  auth_token:
    secure: eqU+9EQfDVZEHnsu/5/FAXLG616PBsTpsGEecKEIKptjNubdISf27ZSsYs4Gmwwe
  artifact: buildzip
  draft: true
